# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - linux64
          - linuxarm
          - macos-x64
          - macos-arm
        include:
          - build: linux64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: linuxarm
            os: ubuntu-latest
            target: arm-unknown-linux-gnu
          - build: macos-x64
            os: macos-latest
          - build: macos-arm
            os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: zmre
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build
